<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\ImsShopGoods */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Ims Shop Goods', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="ims-shop-goods-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'uniacid',
            'pcate',
            'ccate',
            'type',
            'status',
            'displayorder',
            'title',
            'thumb',
            'unit',
            'description',
            'content:ntext',
            'goodssn',
            'productsn',
            'productprice',
            'marketprice',
            'costprice',
            'originalprice',
            'total',
            'totalcnf',
            'sales',
            'salesreal',
            'spec',
            'createtime:datetime',
            'weight',
            'credit',
            'maxbuy',
            'usermaxbuy',
            'hasoption',
            'dispatch',
            'thumb_url:ntext',
            'isnew',
            'ishot',
            'isdiscount',
            'isrecommand',
            'issendfree',
            'istime:datetime',
            'iscomment',
            'timestart:datetime',
            'timeend:datetime',
            'viewcount',
            'deleted',
            'hascommission',
            'commission1_rate',
            'commission1_pay',
            'commission2_rate',
            'commission2_pay',
            'commission3_rate',
            'commission3_pay',
            'score',
            'taobaoid',
            'taotaoid',
            'taobaourl',
            'updatetime:datetime',
            'share_title',
            'share_icon',
            'cash',
            'commission_thumb',
            'isnodiscount',
            'showlevels:ntext',
            'buylevels:ntext',
            'showgroups:ntext',
            'buygroups:ntext',
            'isverify',
            'storeids:ntext',
            'noticeopenid',
            'tcate',
            'noticetype:ntext',
            'needfollow',
            'followtip',
            'followurl',
            'deduct',
            'virtual',
            'ccates:ntext',
            'discounts:ntext',
            'nocommission',
            'hidecommission',
            'pcates:ntext',
            'tcates:ntext',
            'cates:ntext',
            'artid',
            'detail_logo',
            'detail_shopname',
            'detail_btntext1',
            'detail_btnurl1',
            'detail_btntext2',
            'detail_btnurl2',
            'detail_totaltitle',
            'isdiscount_title',
            'isdiscount_time:datetime',
            'isdiscount_discounts:ntext',
            'commission:ntext',
            'saleupdate42392',
            'deduct2',
            'ednum',
            'saleupdate',
            'edmoney',
            'edareas:ntext',
            'diyformtype',
            'diyformid',
            'diymode',
            'dispatchtype',
            'dispatchid',
            'dispatchprice',
            'manydeduct',
            'shorttitle',
            'saleupdate37975',
            'shopid',
            'allcates:ntext',
            'minbuy',
            'invoice',
            'repair',
            'seven',
            'money',
            'minprice',
            'maxprice',
            'province',
            'city',
            'buyshow',
            'buycontent:ntext',
            'saleupdate51117',
            'virtualsend',
            'virtualsendcontent:ntext',
            'verifytype',
            'diyfields:ntext',
            'diysaveid',
            'diysave',
            'quality',
            'groupstype',
            'showtotal',
            'subtitle',
            'minpriceupdated',
            'sharebtn',
            'catesinit3:ntext',
            'showtotaladd',
            'merchid',
            'checked',
            'thumb_first',
            'merchsale',
            'keywords',
            'catch_id',
            'catch_url:url',
            'catch_source',
            'saleupdate40170',
            'saleupdate35843',
            'labelname:ntext',
            'autoreceive',
            'cannotrefund',
            'saleupdate33219',
            'bargain',
            'buyagain',
            'buyagain_islong',
            'buyagain_condition',
            'buyagain_sale',
            'buyagain_commission:ntext',
            'saleupdate32484',
            'saleupdate36586',
            'diypage',
            'cashier',
            'saleupdate53481',
            'saleupdate30424',
            'isendtime:datetime',
            'usetime:datetime',
            'endtime:datetime',
            'merchdisplayorder',
            'exchange_stock',
            'exchange_postage',
            'ispresell',
            'presellprice',
            'presellover',
            'presellovertime:datetime',
            'presellstart',
            'preselltimestart:datetime',
            'presellend',
            'preselltimeend:datetime',
            'presellsendtype',
            'presellsendstatrttime:datetime',
            'presellsendtime:datetime',
            'edareas_code:ntext',
            'unite_total',
            'buyagain_price',
            'threen',
            'intervalfloor',
            'intervalprice',
            'isfullback',
            'isstatustime:datetime',
            'statustimestart:datetime',
            'statustimeend:datetime',
            'nosearch',
            'showsales',
            'islive',
            'liveprice',
            'opencard',
            'cardid',
            'verifygoodsnum',
            'verifygoodsdays',
            'verifygoodslimittype',
            'verifygoodslimitdate',
            'minliveprice',
            'maxliveprice',
            'dowpayment',
            'tempid',
            'isstoreprice',
            'beforehours',
        ],
    ]) ?>

</div>
